// <auto-generated />
namespace Server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class upd19022024 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(upd19022024));
        
        string IMigrationMetadata.Id
        {
            get { return "202402191517466_upd19.02.2024"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
